title: RHEL Troubleshooting Guide
description: A complete guide to RHEL troubleshooting

remote_theme: clearpathrobotics/jekyll-rtd-theme

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: README.md
    values:
      permalink: index.html
